### ISSUE TITLE
statsdUrlKey

### ISSUE THREAD

**Issue by iliuta** [msiebuhr/node-statsd-client#63]
Hi, 

I'm using statsd-client in an express application which exposes a REST API with several endpoints (URLs).

I use statsdUrlKey to distinguish between endpoints and it works great with response times.

Is there any reason why statsdUrlKey is ignored when pushing response_code metrics to statsd?
It could be useful to distinguish the route names for response codes also. Example: compute and display the number of requests for a given endpoint and not the total for all endpoints ...

Thanks for your (future) answer.

**Comment by msiebuhr** [comment]
Good catch. Have a look at this: https://github.com/msiebuhr/node-statsd-client/commit/d78fca8ab9e3a0f4572f38a4aed303581e7050be

**Comment by iliuta** [comment]
Thanks!
Perhaps the option name timeByUrl is a little bit misleading, but basically it does what I expect to do. So that's ok to me.
Do you plan to release it soon?

**Comment by shichongrui** [comment]
I'm not sure if commenting on an already merged commit will trigger any alert but please see my comment on that commit as the new functionality broke total response code counting when using `timeByUrl`. If it is determined that this was not intentional I would be happy to provide a Pull Request that ensures both total counting and counting per endpoint work.
